---
- name: Update Linux boxes
  hosts: NixOS 
  become: true
  gather_facts: true

  tasks:
    - name: Update openSUSE Tumbleweed hosts
      community.general.zypper:
        name: '*'
        state: dist-upgrade
        update_cache: yes
      when:
        - ansible_distribution == "openSUSE Tumbleweed"
      retries: 4
      register: tw_update_status

    - name: Reboot all updated machines and wait for it to boot
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: "whoami"
      when: tw_update_status.changed

    - name: Update SLE/openSUSE Leap hosts
      community.general.zypper:
        name: '*'
        state: latest
        update_cache: yes
      retries: 4
      when:
        - ansible_distribution == "openSUSE Leap"
      register: leap_update_status

    - name: Reboot all updated machines and wait for it to boot
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: "whoami"
      when: leap_update_status.changed

    - name: Update openSUSE MicroOS/Kubic hosts
      community.general.zypper:
        name: '*'
        state: dist-upgrade
        update_cache: yes
      retries: 4
      when:
        - ansible_distribution == "openSUSE MicroOS"
      register: micro_update_status

    - name: Reboot all updated machines and wait for it to boot
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: "whoami"
      when: micro_update_status.changed

    - name: Update RHEL,Fedora,CentOS hosts
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      retries: 4
      when:
        - ansible_os_family == "RedHat"
      register: rhel_update_status

    - name: Reboot all updated machines and wait for it to boot
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: "whoami"
      when: rhel_update_status.changed

    - name: Update Debian/Ubuntu hosts
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
      register: deb_update_status

    - name: Reboot all updated machines and wait for it to boot
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: "whoami"
      when: deb_update_status.changed

    - name: Pull nix configuration from Github (NixOS)
      ansible.builtin.git:
        repo: https://github.com/apinter/dotconf.git
        dest: /tmp/dotconf
        version: master
        single_branch: true
      when:
        - ansible_distribution == "NixOS"

    - name: Copy nix configuration to /etc/nixos (NixOS)
      ansible.builtin.copy:
        src: /tmp/dotconf/nix/{{ inventory_hostname }}
        dest: /etc/nixos
        owner: root
        group: root
        mode: 0755
        remote_src: yes
      when:
        - ansible_distribution == "NixOS"

    - name: Update NixOS hosts
      ansible.builtin.shell: nix-channel --update && nixos-rebuild switch --upgrade
      when:
        - ansible_distribution == "NixOS"
      retries: 4
      register: nix_update_status

    - name: Reboot all updated machines and wait for it to boot
      ansible.builtin.reboot:
        reboot_timeout: 600
        reboot_command: "/run/current-system/sw/bin/reboot"
        test_command: "whoami"
      when: nix_update_status.changed
