name: Automated system update
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 0'

jobs:
  node-update:
    name: Update nodes 
    runs-on: ubuntu-latest
    container:
        image: docker.io/adathor/ansible-runner:latest
        env:
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
    steps:
      - name: Update server
        run: |
            export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            mkdir -p ~/.ssh/
            echo -n ${{ secrets.SSH_SECRET }} > ~/.ssh/ansi
            ansible-playbook -i inventory system_updater.yml -e "target_host=Fedora"

