name: Automated system update
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 0'

jobs:
  node-update:
    name: Update nodes 
    runs-on: ubuntu-latest
    container:
        image: docker.io/adathor/ansible-runner:latest
        env:
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Update server
        run: |
            ls -al
            mkdir -p ~/.ssh/
            echo ${{ secrets.SSH_SECRET }} > ~/.ssh/ansi
            which ansible-playbook
            #/usr/bin/ansible-playbook -i inv.ini system_updater.yml -e "target_host=Fedora"

