name: Automated system update
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 0'

jobs:
  node-update:
    name: Update nodes 
    runs-on: ubuntu-latest
    container:
        image: docker.io/adathor/ansible-runner:latest
        env:
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Update server
        run: |
            ls -al
            export ANSIBLE_CALLBACK_PLUGINS=$(python3 -m ara.setup.callback_plugins)
            export ARA_API_CLIENT=http
            export ARA_API_SERVER="https://ara.adathor.com"
            export ARA_API_USERNAME=dataricecrispygoat
            export ARA_API_PASSWORD=${{ secrets.ARA_API_PW }}
            mkdir -p ~/.ssh/
            echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/ansi && chmod 0600 ~/.ssh/ansi
            ansible-playbook -i inv.yml system_updater.yml -e "target_host=Fedora"

